[directory]
truncate_to_repo = false

[directory.substitutions]
"~/github" = "github.com"

[gcloud]
disabled = true



[nodejs]
format = "using [$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = " "
